### ISSUE TITLE
box 'ubuntu/xenial64' could not be found

### ISSUE THREAD

**Issue by kination** [martinprobson/vagrant-hadoop-hive-spark#12]
First, thanks for your work.
I just tried your file, but it shows error like:
```
$ vagrant up
Bringing machine 'node1' up with 'virtualbox' provider...
==> node1: Box 'ubuntu/xenial64' could not be found. Attempting to find and install...
    node1: Box Provider: virtualbox
    node1: Box Version: >= 0
The box 'ubuntu/xenial64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/ubuntu/xenial64"]
Error: The requested URL returned error: 404 Not Found
```
Is the path changed?

**Comment by kination** [comment]
Oh, sorry. It was the problem of my vagrant version. It works find after update to newest one.

**Comment by kination** [comment]
I just found something while setting up hive, but not sure if this is a problem or not.

```
...
node1: setup hive
    node1: install hive from remote file
    node1: c
    node1: u
    node1: r
    node1: l
    node1: :
    node1:  
    node1: (
    node1: 1
    node1: 8
    node1: )
    node1:  
    node1: t
    node1: r
    node1: a
    node1: n
    node1: s
    node1: f
    node1: e
    node1: r
    node1:  
    node1: c
    node1: l
    node1: o
    node1: s
    node1: e
    node1: d with 211282726 bytes remaining to read
    node1: 
    node1: gzip: stdin: unexpected end of file
    node1: tar: 
    node1: Unexpected EOF in archive
    node1: tar: 
    node1: Unexpected EOF in archive
    node1: tar: 
    node1: Error is not recoverable: exiting now
    node1: copying over hive configuration file
    node1: creating hive environment variables
    node1: running hive metastore
    node1: running hive server2
    node1: hive setup complete
==> node1: Running provisioner: shell...
...
```
Any information?

**Comment by martinprobson** [comment]
Hi djKooks,
Yes, that is a problem, looks like curl had a problem downloading hive from remote site. You could do a `vagrant destroy` and then a `vagrant up` to re-try building the box again.
If that still does not work then you could try downloading the hive tar manually. 
1) Go to the apache hive download page [here](http://www.apache.org/dyn/closer.cgi/hive/)
2) It should suggest a mirror suitable for your location. 
3) For spark 2.1.1 version of the box download `apache-hive-2.1.1-bin.tar.gz` and place it in the resources directory.
4) For spark 2.3.3 version of the box download `apache-hive-2.3.3-bin.tar.gz` and place it in the resources directory.
5) The installation scripts will then use the cached copy of the download rather than attempting to download.

Hopefully that should work for you.

**Comment by kination** [comment]
@macunha1 Thanks. It seems this error has been passing now.
I'll reopen it if I found any other stuffs. Thanks.
